with listen_events as (
    select * from {{ ref('int_streamify__listen_events') }}
)

select distinct
    state as state_id,
    case lower(trim(state))
        when 'nv' then 'Nevada'
        when 'ar' then 'Arkansas'
        when 'ct' then 'Connecticut'
        when 'mi' then 'Michigan'
        when 'sd' then 'South Dakota'
        when 'nj' then 'New Jersey'
        when 'dc' then 'District of Columbia'
        when 'ia' then 'Iowa'
        when 'nd' then 'North Dakota'
        when 'wi' then 'Wisconsin'
        when 'tx' then 'Texas'
        when 'id' then 'Idaho'
        when 'ak' then 'Alaska'
        when 'ma' then 'Massachusetts'
        when 'va' then 'Virginia'
        when 'wv' then 'West Virginia'
        when 'mo' then 'Missouri'
        when 'ks' then 'Kansas'
        when 'hi' then 'Hawaii'
        when 'md' then 'Maryland'
        when 'az' then 'Arizona'
        when 'wa' then 'Washington'
        when 'pa' then 'Pennsylvania'
        when 'la' then 'Louisiana'
        when 'il' then 'Illinois'
        when 'de' then 'Delaware'
        when 'ms' then 'Mississippi'
        when 'ri' then 'Rhode Island'
        when 'me' then 'Maine'
        when 'ut' then 'Utah'
        when 'oh' then 'Ohio'
        when 'wy' then 'Wyoming'
        when 'ky' then 'Kentucky'
        when 'mn' then 'Minnesota'
        when 'sc' then 'South Carolina'
        when 'co' then 'Colorado'
        when 'nm' then 'New Mexico'
        when 'nh' then 'New Hampshire'
        when 'nc' then 'North Carolina'
        when 'ca' then 'California'
        when 'fl' then 'Florida'
        when 'al' then 'Alabama'
        when 'ok' then 'Oklahoma'
        when 'tn' then 'Tennessee'
        when 'ga' then 'Georgia'
        when 'ny' then 'New York'
        when 'or' then 'Oregon'
        when 'in' then 'Indiana'
        when 'ne' then 'Nebraska'
        when 'vt' then 'Vermont'
        when 'mt' then 'Montana'
        else 'Unknown'
    end as state_name,
    case
        when lower(trim(state)) in ('ct', 'me', 'ma', 'nh', 'ri', 'vt', 'nj', 'ny', 'pa') then 'Northeast'
        when lower(trim(state)) in ('il', 'in', 'mi', 'oh', 'wi', 'ia', 'ks', 'mn', 'mo', 'ne', 'nd', 'sd') then 'Midwest'
        when lower(trim(state)) in ('de', 'fl', 'ga', 'md', 'nc', 'sc', 'va', 'dc', 'wv', 'al', 'ky', 'ms', 'tn', 'ar', 'la', 'ok', 'tx') then 'South'
        when lower(trim(state)) in ('az', 'co', 'id', 'mt', 'nv', 'nm', 'ut', 'wy', 'ak', 'ca', 'hi', 'or', 'wa') then 'West'
        else 'Unknown'
    end as region
from listen_events
where state is not null
